# Generated by Django 6.0.1 on 2026-01-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="Price",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
